version: '2.1'
services:
    api:
        volumes:
            - "${SOURCE_DIR}/backend-api:/src"
            - "${SOURCE_DIR}/module-lucius:/module-lucius"
            - "${SOURCE_DIR}/module-logger:/module-logger"
            - "${SOURCE_DIR}/module-service-factory:/module-service-factory"
        env_file:
            - ${SERVICE_DIR}/backend-api/.env
            - ./.env
        ports:
            - "${API_EXPOSED_PORT}:${API_PORT}"
            - "${DEBUG_EXPOSED_PORT_API}:${DEBUG_PORT}"
        links:
            - auth
        build:
            context: .
            dockerfile: Dockerfile-node
        #environment:
        #extends:
            #service: api
    auth:
        volumes:
            - "${SOURCE_DIR}/backend-auth:/src"
            - "${SOURCE_DIR}/module-lucius:/module-lucius"
            - "${SOURCE_DIR}/module-logger:/module-logger"
            - "${SOURCE_DIR}/module-service-factory:/module-service-factory"
        env_file:
            - ${SERVICE_DIR}/backend-auth/.env
            - ./.env
        ports:
            - "${DEBUG_EXPOSED_PORT_AUTH}:${DEBUG_PORT}"
        links:
            - db
        build:
            context: .
            dockerfile: Dockerfile-node
    db:
        volumes:
            - "${SOURCE_DIR}/backend-db:/src"
            - "${SOURCE_DIR}/module-lucius:/module-lucius"
            - "${SOURCE_DIR}/module-logger:/module-logger"
            - "${SOURCE_DIR}/module-service-factory:/module-service-factory"
        env_file:
            - ${SERVICE_DIR}/backend-db/.env
            - ./.env
        ports:
            - "${DEBUG_EXPOSED_PORT_DB}:${DEBUG_PORT}"
        links:
            - couchbase
        build:
            context: .
            dockerfile: Dockerfile-node
    couchbase:
        env_file:
            - ${SERVICE_DIR}/couchbase/.env
            - ./.env
        image: couchbase/server:community-4.5.1
        ports:
            - "8091:8091"
            #- "8091-8094:8091-8094"
            #- "11210:11210"
        volumes:
            - ./services/couchbase/lib:/opt/couchbase/var/lib/couchbase
            - ./services/couchbase/local.ini:/opt/couchbase/etc/couchdb/local.ini
